site_name: Talus Bio @ ASMS
site_url: https://talusbio.github.io/talusbio-at-asms
description: ASMS presentations and events from Talus Bio and Collaborators

theme:
  name: material
  favicon: static/talus-logo.svg
  logo: static/talus-logo.svg
  font:
    text: IBM Plex Sans
  features:
     - toc.integrate
  palette:
    scheme: talusbio

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - smarty
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/talusbio

plugins:
  - search
  - social:
      cards_layout_options:
        font_family: "IBM Plex Sans"
