site_name: Talus Bio @ ASMS

theme:
  name: material
  favicon: static/talus-logo.svg
  logo: static/talus-logo.svg
  font:
    text: IBM Plex Sans
  features:
     - toc.integrate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - smarty
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/talusbio

plugins:
  - search
  - social
